"""initial db

Revision ID: 2433df516ecd
Revises: 
Create Date: 2025-09-02 18:47:27.749249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2433df516ecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date_time',
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('usa_session', sa.Boolean(), nullable=False),
    sa.Column('london_session', sa.Boolean(), nullable=False),
    sa.Column('tokyo_session', sa.Boolean(), nullable=False),
    sa.Column('sydney_session', sa.Boolean(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date_time')
    )
    op.create_index(op.f('ix_dim_date_time_date_time'), 'dim_date_time', ['date_time'], unique=False)
    op.create_table('dim_time_frame',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('included_1m', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('included_1m')
    )
    op.create_table('flags',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_first_run', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_name', sa.String(length=16), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('quote_currency', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_name')
    )
    op.create_table('dim_candle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('time_frame_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_time'], ['dim_date_time.date_time'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.ForeignKeyConstraint(['time_frame_id'], ['dim_time_frame.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_candle')
    op.drop_table('symbol')
    op.drop_table('flags')
    op.drop_table('dim_time_frame')
    op.drop_index(op.f('ix_dim_date_time_date_time'), table_name='dim_date_time')
    op.drop_table('dim_date_time')
    # ### end Alembic commands ###
